name: Presubmit

on: [pull_request]

jobs:
  build-desktop:
    name: build-desktop
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Filament
        run: |
          git version
          git init $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git remote add origin https://github.com/google/filament
          git config gc.auto 0
          git fetch --tags --prune --progress --no-recurse-submodules origin +${GITHUB_REF}:${GITHUB_REF/refs\//refs\/remote\/}
          git checkout --progress --force ${GITHUB_REF/refs\//refs\/remote\/}
      - name: Run build script
        if: matrix.os == 'macos-latest'
        run: |
          cd build/mac && ./build.sh ${TARGET}
        env:
          TARGET: presubmit
      - name: Run build script
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd build/linux && ./build.sh ${TARGET}
        env:
          TARGET: presubmit
      - name: Run build script
        if: matrix.os == 'windows-latest'
        run: |
          cd build/windows && ./build.sh ${TARGET}
        env:
          TARGET: presubmit

  build-android:
    name: build-android
    runs-on: macos-latest

    steps:
      - name: Checkout Filament
        run: |
          git version
          git init $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git remote add origin https://github.com/google/filament
          git config gc.auto 0
          git fetch --tags --prune --progress --no-recurse-submodules origin +${GITHUB_REF}:${GITHUB_REF/refs\//refs\/remote\/}
          git checkout --progress --force ${GITHUB_REF/refs\//refs\/remote\/}
      - name: Run build script
        run: |
          cd build/android && ./build.sh ${TARGET}
        env:
          TARGET: presubmit

  build-ios:
    name: build-iOS
    runs-on: macos-latest

    steps:
      - name: Checkout Filament
        run: |
          git version
          git init $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git remote add origin https://github.com/google/filament
          git config gc.auto 0
          git fetch --tags --prune --progress --no-recurse-submodules origin +${GITHUB_REF}:${GITHUB_REF/refs\//refs\/remote\/}
          git checkout --progress --force ${GITHUB_REF/refs\//refs\/remote\/}
      - name: Run build script
        run: |
          cd build/ios && ./build.sh ${TARGET}
        env:
          TARGET: presubmit

  build-web:
    name: build-web
    runs-on: macos-latest

    steps:
      - name: Checkout Filament
        run: |
          git version
          git init $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          git remote add origin https://github.com/google/filament
          git config gc.auto 0
          git fetch --tags --prune --progress --no-recurse-submodules origin +${GITHUB_REF}:${GITHUB_REF/refs\//refs\/remote\/}
          git checkout --progress --force ${GITHUB_REF/refs\//refs\/remote\/}
      - name: Run build script
        run: |
          cd build/web && ./build.sh ${TARGET}
        env:
          TARGET: presubmit
